apiVersion: v1
kind: Secret
metadata:
  name: alcoyano-secrets
type: Opaque
data:
  GIT_TOKEN: {{ .Values.alcoyano.github.token | b64enc | quote }}
  MINIO_ACCESS_KEY: {{ .Values.alcoyano.minio.accessKey | b64enc | quote }}
